services:
  email-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
      # Optional environment variables
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_PORT=${SERVER_PORT}
    restart: unless-stopped
    networks:
      - email-network

networks:
  email-network:
    driver: bridge
